apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::629638513518:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1NR6B3IMLO4MZ
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::629638513518:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-23T23:23:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1501"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: b6ed0831-7e37-48ca-87a7-f6d0fb7f4125
